### ISSUE TITLE
“Cannot find program” error.

### ISSUE THREAD

**Issue by andrewhayes1979** [doomhack/PsionDoom#1]
Hi

Kudos for porting this to the venerable Psion 5...I've recently acquired the Game Engine Black Book for DOOM and am interested in seeing how it runs these days on ancient hardware.

I've followed the instructions on the release notes, but I'm not able to get it running on my old, trusty Psion 5mx:

- I've downloaded the 7z archive, unpacked this
- Copied the extracted folder to a compact flash card into a "Doom" folder at the root (respecting the case listed in the instructions)
- mounted the card into the Psion
- navigated to D:/Doom/ via the system browser
- I see 4 items, DOOM1.WAD, PRBOOM.WAD, PSIONDOOM.EXE and TRANMAP.DAT, and there's a folder called DGGUSPAT that appears to contain MIDI instruments
- the 4 items all have "?" icons as their document icon
- clicking PSIONDOOM.EXE just displays a "Cannot find program" flash message...the system is trying to locate an app on the system that can run EXE files...but there isn't one

So...how do you run it? Am I missing something?

I thought Psion apps were bundled into SIS installation archives? :-/

**Comment by andrewhayes1979** [comment]
...or is this not for running on EPOC32, and actually for some Linux port to Psion hardware?

**Comment by andrewhayes1979** [comment]
Looking at the source, seems it is a Psion project (there's EIKON in there for UI, an .mmp file)

(I used to be a Symbian developer many years ago)

Isn't the executable for devices (pre Symbian 7) an app file with a .app file extension...have you shipped the WINS emulator executable in the archive?

**Comment by doomhack** [comment]
Wow! Someone actually tried it!

I think you don't have the stdlib installed. There is a copy here:
https://github.com/doomhack/PsionDoom/tree/master/redist

I don't think it came as part of the ROM on the 5.

The .exe is the right file. .app files are for Eikon applications whereas .exe's don't integrate into the shell and therefore don't have to deal with all of the limitations like no global vars.

**Comment by doomhack** [comment]
To resolve this error:

1) Open control panel on your device.
2) Check if there is an icon for “Add/Remove”.
2a) If not, download and copy ‘instexe.exe’ to your CF card. Run on device to install the “Add/Remove” control panel icon. (https://github.com/doomhack/PsionDoom/tree/master/redist)
3) Install ‘stdlib.sis’ on your device. This is the Psion C runtime lib. (Download above or included with 0.2 release).

You should now be able to play.
